version: "3.7"
services:
  minio_config:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/video;
      #/usr/bin/mc policy set public myminio/video;
      exit 0;
      "
    networks:
      - stroygetter

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2023
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER:-user}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-password}"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./containers/minio:/data:rw
    networks:
      - stroygetter

networks:
  stroygetter:
    driver: bridge
