name: Build & publish the extension

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@master
        with:
          ref: prod
          fetch-depth: 0
      - name: Move on extension directory
        run: cd stroygetter_extension
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Move on extension directory
        run: cd stroygetter_extension
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - id: packExtensionDir
        name: Pack extension directory
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "./dist"
          zipFilePath: "build/extension.zip"
      - name: Build extension CRX
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: "build/extension.zip"
          crxFilePath: "./stroygetter_extension.crx"
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }}
      - name: Upload extension CRX
        uses: actions/upload-artifact@v2
        with:
          name: stroygetter-extension-crx
          path: stroygetter_extension.crx
