name: Create tag from commit message

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: prod
          fetch-depth: 0

      - name: Get version from last commit message
        id: commit
        run: |
          MESSAGE=$(git log -1 --pretty=format:'%s')
          CLEANED=$(echo "$MESSAGE" | sed -e 's/[^a-zA-Z0-9.-]/-/g')
          echo "tag=${CLEANED}" >> "$GITHUB_OUTPUT"

      - name: Create or update tag
        uses: joutvhu/create-tag@v1
        with:
          tag_name: ${{ steps.commit.outputs.tag }}
          message: ${{ steps.commit.outputs.tag }}
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
