name: Release pipeline

on:
  push:
    branches:
      - prod
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-release]

jobs:
  create_tag:
    uses: ./.github/workflows/create_tag.yml
    secrets: inherit
  build_app:
    needs: create_tag
    uses: ./.github/workflows/build_web_image.yml
    secrets: inherit
  deploy_release:
    needs: [create_tag, build_app]
    uses: ./.github/workflows/create_release.yml
    secrets: inherit
