name: Deploy pre-release image

on:
  workflow_call:
    inputs:
      tag:
        description: Tag to use for the image
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to use for the image
        required: false

permissions:
  contents: read

jobs:
  docker:
    name: Build & push pre-release image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Write .env file
        env:
          ENVFILE: ${{ secrets.ENVFILE }}
        run: echo "$ENVFILE" > .env

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: destcom/stroygetter
          tags: type=raw,value=${{ inputs.tag || 'alpha' }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
