name: Scheduled tests

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm prisma generate

      - run: pnpm vitest run --reporter=verbose --reporter=junit --outputFile=test-results/junit.xml

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: All Tests
          path: test-results/junit.xml
          reporter: jest-junit
